### ISSUE TITLE
data point, compile works on slackware linux, upload fails

### ISSUE THREAD

**Issue by jmarca** [noopkat/jewelbots-autodev#6]
On Linux (slackware 14.2), I have the following .jbauto file, that works.  Also, I found that using ~ didn't resolve properly to `/home/james`...my first version had the jewelbots lib at `~/.arduino15...`.

```
{
  "jewelbots-lib": "/home/james/.arduino15/packages/Jewelbots_Arduino_Library",
  "arduino-app": "/opt/arduino",
  "build-destination": "dist",
  "sketch-file": "jingle_bells.ino"
}
```

But uploading it fails:

```
jewelbots-autodev upload
(node:23084) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'filter' of undefined
(node:23084) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

node version v7.2.0

**Comment by jmarca** [comment]
I think I can hack on this.  Seems it isn't finding the serial ports to filter through.  I'll work on my fork and see if I can fix it.

**Comment by jmarca** [comment]
Upstream issue with node-serialport.  I reported the issue there.  Essentially, slackware doesn't expose /sbin and /usr/sbin to non-privileged user's PATH.  So /sbin/udevadm isn't visible, and serialport can't use it.  The fix for me (besides reporting the issue upstream) is to symlink /sbin/udevadm to my local path, or 

```
ln -sf /sbin/udevadm ~/bin/.
```

Then at least this bug is fixed.  But I've got a new bug:

```
james@emma jewelbots_sketches$ jewelbots-autodev upload
found jewelbot on port /dev/ttyUSB0
Error: sorry, uploading to Jewelbot is not currently supported on Linux
    at /usr/local/lib/node_modules/jewelbots-autodev/lib/uploader.js:39:25
    at FSReqWrap.cb [as oncomplete] (fs.js:239:19)
```

meh.

But I'm going to close this issue because I got the ports to list at least.
